# Generated by Django 6.0.5 on 2026-05-23 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('turma', models.CharField(help_text='Ex: 3A, ou "todas"', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateTimeField()),
                ('arquivo_enunciado', models.FileField(blank=True, null=True, upload_to='tarefas/enunciados/')),
                ('criterios', models.TextField(blank=True, help_text='Critérios de avaliação')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada')], default='aberta', max_length=10)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='tarefas/entregas/')),
                ('comentario', models.TextField(blank=True)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tarefas.tarefa')),
            ],
            options={
                'unique_together': {('tarefa', 'aluno')},
            },
        ),
    ]
